### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SeolJaeHyeok** [SeolJaeHyeok/MyBlog#1]
- [ ] UI 및 사용자 기능 개선 

- [X] Code Splitting

- [ ] Hosting - netlify 말고 AWS 사용해보기

- [ ] SSR - 초기 렌더링 성능 개선
